apiVersion: batch/v1
kind: Job
metadata:
  name: diag-network
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: diag-tool
          image: suhannugul/capstonetest:latest
          args: ["network"]
